name 'teleport'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Application cookbook which installs and configures Teleport.'
long_description 'Application cookbook which installs and configures Teleport.'
version '1.0.0'
source_url 'https://github.com/johnbellone/teleport-cookbook'
issues_url 'https://github.com/johnbellone/teleport-cookbook/issues'

supports 'ubuntu', '>= 12.04'
supports 'centos', '>= 5.8'
supports 'redhat', '>= 5.8'

depends 'poise-archive', '~> 1.1'
